service: winnow-serverless-project

custom:
  tableName: "users-table-${self:provider.stage}"

provider:
  name: aws
  runtime: nodejs8.9
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["usersTable", "Arn"] }
  environment:
    USERS_TABLE: ${self:custom.tableName}

environment:
  NODE_ENV: ${self:provider.stage}

resources: # CloudFormation template syntax
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
